import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:islami/app_colors.dart';
import 'package:islami/quran/item_sura_name.dart';
import 'package:provider/provider.dart';

import '../providers/app_config_provider.dart';

class QuranTab extends StatelessWidget {
  List<String> names = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  List<String> suraType = [
    "1 - مكية",
    "2 - مدنية",
    "3 - مدنية",
    "4 - مدنية",
    "5 - مدنية",
    "6 - مكية",
    "7 - مكية",
    "8 - مدنية",
    "9 - مدنية",
    "10 - مكية",
    "11 - مكية",
    "12 - مكية",
    "13 - مدنية",
    "14 - مكية",
    "15 - مكية",
    "16 - مكية",
    "17 - مكية",
    "18 - مكية",
    "19 - مكية",
    "20 - مكية",
    "21 - مكية",
    "22 - مدنية",
    "23 - مكية",
    "24 - مدنية",
    "25 - مكية",
    "26 - مكية",
    "27 - مكية",
    "28 - مكية",
    "29 - مكية",
    "30 - مكية",
    "31 - مكية",
    "32 - مكية",
    "33 - مدنية",
    "34 - مكية",
    "35 - مكية",
    "36 - مكية",
    "37 - مكية",
    "38 - مكية",
    "39 - مكية",
    "40 - مكية",
    "41 - مكية",
    "42 - مكية",
    "43 - مكية",
    "44 - مكية",
    "45 - مكية",
    "46 - مكية",
    "47 - مدنية",
    "48 - مدنية",
    "49 - مدنية",
    "50 - مكية",
    "51 - مكية",
    "52 - مكية",
    "53 - مكية",
    "54 - مكية",
    "55 - مدنية",
    "56 - مكية",
    "57 - مدنية",
    "58 - مدنية",
    "59 - مدنية",
    "60 - مدنية",
    "61 - مدنية",
    "62 - مدنية",
    "63 - مدنية",
    "64 - مدنية",
    "65 - مدنية",
    "66 - مدنية",
    "67 - مكية",
    "68 - مكية",
    "69 - مكية",
    "70 - مكية",
    "71 - مكية",
    "72 - مكية",
    "73 - مكية",
    "74 - مكية",
    "75 - مكية",
    "76 - مدنية",
    "77 - مكية",
    "78 - مكية",
    "79 - مكية",
    "80 - مكية",
    "81 - مكية",
    "82 - مكية",
    "83 - مكية",
    "84 - مكية",
    "85 - مكية",
    "86 - مكية",
    "87 - مكية",
    "88 - مكية",
    "89 - مكية",
    "90 - مكية",
    "91 - مكية",
    "92 - مكية",
    "93 - مكية",
    "94 - مكية",
    "95 - مكية",
    "96 - مكية",
    "97 - مكية",
    "98 - مدنية",
    "99 - مدنية",
    "100 - مكية",
    "101 - مكية",
    "102 - مكية",
    "103 - مكية",
    "104 - مكية",
    "105 - مكية",
    "106 - مكية",
    "107 - مكية",
    "108 - مكية",
    "109 - مكية",
    "110 - مدنية",
    "111 - مكية",
    "112 - مكية",
    "113 - مكية",
    "114 - مكية",
  ];

  QuranTab({super.key});

  @override
  Widget build(BuildContext context) {
    var provider = Provider.of<AppConfigProvider>(context);
    return Column(
      children: [
        Expanded(
          child: Image.asset('assets/images/quran_logo-1x.png'),
        ),
        Divider(
          color: provider.isDarkMode()
              ? AppColors.brownColor
              : AppColors.primaryLightColor,
          thickness: 2,
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Text(
              AppLocalizations.of(context)!.sura_name,
              style: Theme.of(context).textTheme.titleMedium,
            ),
            Container(
              height: MediaQuery.of(context).size.height * 0.05,
              width: MediaQuery.of(context).size.width * 0.006,
              color: provider.isDarkMode()
                  ? AppColors.brownColor
                  : AppColors.primaryLightColor,
            ),
            Text(
              AppLocalizations.of(context)!.sura_type,
              style: Theme.of(context).textTheme.titleMedium,
            ),
          ],
        ),
        Divider(
          color: provider.isDarkMode()
              ? AppColors.brownColor
              : AppColors.primaryLightColor,
          thickness: 2,
        ),
        Expanded(
          flex: 2,
          child: ListView.separated(
            separatorBuilder: (context, index) {
              return Divider(
                color: provider.isDarkMode()
                    ? AppColors.brownColor
                    : AppColors.primaryLightColor,
                thickness: 2,
              );
            },
            itemBuilder: (context, index) {
              return ItemSuraName(
                type: suraType[index],
                name: names[index],
                index: index,
              );
            },
            itemCount: names.length,
          ),
        )
      ],
    );
  }
}
